
spring:
  servlet:
    multipart:
      max-file-size: 512MB

graphql:
  servlet:
    maxQueryDepth: 100
    exception-handlers-enable: true
  playground:
    headers:
      Authorization: Bearer TOKEN
      user_id: TEST USER
    tabs:
      - name: Account sample query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json
      - name: Account sample mutation
        query: classpath:playground/create_account.graphql
        variables: classpath:playground/create_account_var.json